config/routes.rb
Rails.application.routes.draw do
  resources :professors
  resources :disciplinas
  resources :areas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
end

app/models/disciplina.rb
class Disciplina < ApplicationRecord
end

app/models/professor.rb
class Professor < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]

  # GET /areas
  # GET /areas.json
  def index
    @areas = Area.all
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
  end

  # GET /areas/new
  def new
    @area = Area.new
  end

  # GET /areas/1/edit
  def edit
  end

  # POST /areas
  # POST /areas.json
  def create
    @area = Area.new(area_params)

    respond_to do |format|
      if @area.save
        format.html { redirect_to @area, notice: 'Area was successfully created.' }
        format.json { render :show, status: :created, location: @area }
      else
        format.html { render :new }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /areas/1
  # PATCH/PUT /areas/1.json
  def update
    respond_to do |format|
      if @area.update(area_params)
        format.html { redirect_to @area, notice: 'Area was successfully updated.' }
        format.json { render :show, status: :ok, location: @area }
      else
        format.html { render :edit }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    @area.destroy
    respond_to do |format|
      format.html { redirect_to areas_url, notice: 'Area was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_area
      @area = Area.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def area_params
      params.require(:area).permit(:Nome)
    end
end

app/controllers/disciplinas_controller.rb
class DisciplinasController < ApplicationController
  before_action :set_disciplina, only: [:show, :edit, :update, :destroy]

  # GET /disciplinas
  # GET /disciplinas.json
  def index
    @disciplinas = Disciplina.all
  end

  # GET /disciplinas/1
  # GET /disciplinas/1.json
  def show
  end

  # GET /disciplinas/new
  def new
    @disciplina = Disciplina.new
  end

  # GET /disciplinas/1/edit
  def edit
  end

  # POST /disciplinas
  # POST /disciplinas.json
  def create
    @disciplina = Disciplina.new(disciplina_params)

    respond_to do |format|
      if @disciplina.save
        format.html { redirect_to @disciplina, notice: 'Disciplina was successfully created.' }
        format.json { render :show, status: :created, location: @disciplina }
      else
        format.html { render :new }
        format.json { render json: @disciplina.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /disciplinas/1
  # PATCH/PUT /disciplinas/1.json
  def update
    respond_to do |format|
      if @disciplina.update(disciplina_params)
        format.html { redirect_to @disciplina, notice: 'Disciplina was successfully updated.' }
        format.json { render :show, status: :ok, location: @disciplina }
      else
        format.html { render :edit }
        format.json { render json: @disciplina.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /disciplinas/1
  # DELETE /disciplinas/1.json
  def destroy
    @disciplina.destroy
    respond_to do |format|
      format.html { redirect_to disciplinas_url, notice: 'Disciplina was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_disciplina
      @disciplina = Disciplina.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def disciplina_params
      params.require(:disciplina).permit(:Nome_disciplina, :Turma, :Dias_de_aula, :Horario)
    end
end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  before_action :set_professor, only: [:show, :edit, :update, :destroy]

  # GET /professors
  # GET /professors.json
  def index
    @professors = Professor.all
  end

  # GET /professors/1
  # GET /professors/1.json
  def show
  end

  # GET /professors/new
  def new
    @professor = Professor.new
  end

  # GET /professors/1/edit
  def edit
  end

  # POST /professors
  # POST /professors.json
  def create
    @professor = Professor.new(professor_params)

    respond_to do |format|
      if @professor.save
        format.html { redirect_to @professor, notice: 'Professor was successfully created.' }
        format.json { render :show, status: :created, location: @professor }
      else
        format.html { render :new }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /professors/1
  # PATCH/PUT /professors/1.json
  def update
    respond_to do |format|
      if @professor.update(professor_params)
        format.html { redirect_to @professor, notice: 'Professor was successfully updated.' }
        format.json { render :show, status: :ok, location: @professor }
      else
        format.html { render :edit }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /professors/1
  # DELETE /professors/1.json
  def destroy
    @professor.destroy
    respond_to do |format|
      format.html { redirect_to professors_url, notice: 'Professor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_professor
      @professor = Professor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def professor_params
      params.require(:professor).permit(:Nome)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/disciplinas_helper.rb
module DisciplinasHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/views/areas/_form.html.erb
<%= form_with(model: area, local: true) do |form| %>
  <% if area.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(area.errors.count, "error") %> prohibited this area from being saved:</h2>

      <ul>
      <% area.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Nome %>
    <%= form.text_field :Nome %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/areas/edit.html.erb
<html lang="pt-br">
   <body>
 
    <header class="header">
         <h3>Estágio<span>Pró</span></h3>
         <p>Alocação de Estagiários Docentes</p>
   
     </header>
 

<h1>Editar Area</h1>

<div class="form">
<%= render 'form', area: @area %>

<button type="button" class="btn btn-primary"><%= link_to 'Exibir', @area %> </button>
<button type="button" class="btn btn-primary"><%= link_to 'Voltar', areas_path %></button>

</div>
 <footer class="footer">

			<div class="footer-left">

				<h3>Estágio<span>Pró</span></h3>

				<p class="footer-company-name">EstagioPró &copy; 2018</p>
			</div>

			<div class="footer-center">

				<div>
					<i class="fa fa-map-marker"></i>
					<p><span>Universidade Federal da Bahia <br> 
                        Instituto de Matemática <br>
                        Departamento de Ciência da COmputação <br>
                        PGComp  - Programa de Pós Graduação em CIência da Computação </span>
				</div>

				<div>
					<i class="fa fa-phone"></i>
					<p>Telefone: +55 (71) 3283-6273 / +55 (71) 3283-6308 <br>
					Fax: +55 (71) 3283-6276</p>
				</div>

				<div>
					<i class="fa fa-envelope"></i>
					<p><a href="mailto:ceapgmat@ufba.br">ceapgmat@ufba.br</a></p>
				</div>

			</div>

			<div class="footer-right">

				<p class="footer-company-address">
					<span>Endereço:</span>
					Centro de Atendimento à Pós-Graduação (CEAPG), Instituto de Matemática e Estatística, Universidade Federal da Bahia - Av. Adhemar de Barros, s/n - Campus de Ondina - 1º Andar - Salvador - Bahia, CEP 40.170-110
				</p>

				

			</div>

		</footer>

 
  </body>
  
</html> 

app/views/areas/index.html.erb
<html lang="pt-br">
   
   <body>
 
     <header class="header">
         <h3>Estágio<span>Pró</span></h3>
         <p>Alocação de Estagiários Docentes</p>
   
     </header>
 

<p id="notice"><%= notice %></p>



    
    


<h1>AREAS</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @areas.each do |area| %>
      <tr>
        <td><%= area.Nome %></td>
        <td><button type="button" class="btn btn-primary"> <%= link_to 'Exibir', area %></button></td>
          <td><button type="button" class="btn btn-secondary"><%= link_to 'Editar', edit_area_path(area) %></button></td>
          <td><button type="button" class="btn btn-danger"><%= link_to 'Deletar', area, method: :delete, data: { confirm: 'Você tem certeza?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button type="button" class="btn btn-success"><%= link_to 'Nova Area', new_area_path %></button>

<footer class="footer">

			<div class="footer-left">

				<h3>Estágio<span>Pró</span></h3>

				<p class="footer-company-name">EstagioPró &copy; 2018</p>
			</div>

			<div class="footer-center">

				<div>
					<i class="fa fa-map-marker"></i>
					<p><span>Universidade Federal da Bahia <br> 
                        Instituto de Matemática <br>
                        Departamento de Ciência da COmputação <br>
                        PGComp  - Programa de Pós Graduação em CIência da Computação </span>
				</div>

				<div>
					<i class="fa fa-phone"></i>
					<p>Telefone: +55 (71) 3283-6273 / +55 (71) 3283-6308 <br>
					Fax: +55 (71) 3283-6276</p>
				</div>

				<div>
					<i class="fa fa-envelope"></i>
					<p><a href="mailto:ceapgmat@ufba.br">ceapgmat@ufba.br</a></p>
				</div>

			</div>

			<div class="footer-right">

				<p class="footer-company-address">
					<span>Endereço:</span>
					Centro de Atendimento à Pós-Graduação (CEAPG), Instituto de Matemática e Estatística, Universidade Federal da Bahia - Av. Adhemar de Barros, s/n - Campus de Ondina - 1º Andar - Salvador - Bahia, CEP 40.170-110
				</p>

				

			</div>

		</footer>


 
  </body>
  
</html> 

app/views/areas/new.html.erb
<html lang="pt-br">
   <body>
 
     <header class="header">
     <h3>Estágio<span>Pró</span></h3>
     <p>Alocação de Estagiários Docentes</p>
   
     </header>
 
    <h1>NOVA AREA</h1>
<div class="form">
   <%= render 'form', area: @area %>

    <button type="submit" class="btn btn-primary"><%= link_to 'Voltar', areas_path %></button> 
</div>
   
   
   <footer class="footer">

			<div class="footer-left">

				<h3>Estágio<span>Pró</span></h3>

				<p class="footer-company-name">EstagioPró &copy; 2018</p>
			</div>

			<div class="footer-center">

				<div>
					<i class="fa fa-map-marker"></i>
					<p><span>Universidade Federal da Bahia <br> 
                        Instituto de Matemática <br>
                        Departamento de Ciência da COmputação <br>
                        PGComp  - Programa de Pós Graduação em CIência da Computação </span>
				</div>

				<div>
					<i class="fa fa-phone"></i>
					<p>Telefone: +55 (71) 3283-6273 / +55 (71) 3283-6308 <br>
					Fax: +55 (71) 3283-6276</p>
				</div>

				<div>
					<i class="fa fa-envelope"></i>
					<p><a href="mailto:ceapgmat@ufba.br">ceapgmat@ufba.br</a></p>
				</div>

			</div>

			<div class="footer-right">

				<p class="footer-company-address">
					<span>Endereço:</span>
					Centro de Atendimento à Pós-Graduação (CEAPG), Instituto de Matemática e Estatística, Universidade Federal da Bahia - Av. Adhemar de Barros, s/n - Campus de Ondina - 1º Andar - Salvador - Bahia, CEP 40.170-110
				</p>

				

			</div>

		</footer>

 
  </body>
  
</html> 

app/views/areas/show.html.erb
<html lang="pt-br">
   <body>
 
    <header class="header">
         <h3>Estágio<span>Pró</span></h3>
         <p>Alocação de Estagiários Docentes</p>
   
     </header>
 


<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @area.Nome %>
</p>

       <button type="button" class="btn btn-primary"><%= link_to 'Editar', edit_area_path(@area) %> </button>
        <button type="button" class="btn btn-secondary"><%= link_to 'Voltar', areas_path %></button>




<footer class="footer">

			<div class="footer-left">

				<h3>Estágio<span>Pró</span></h3>

				<p class="footer-company-name">EstagioPró &copy; 2018</p>
			</div>

			<div class="footer-center">

				<div>
					<i class="fa fa-map-marker"></i>
					<p><span>Universidade Federal da Bahia <br> 
                        Instituto de Matemática <br>
                        Departamento de Ciência da COmputação <br>
                        PGComp  - Programa de Pós Graduação em CIência da Computação </span>
				</div>

				<div>
					<i class="fa fa-phone"></i>
					<p>Telefone: +55 (71) 3283-6273 / +55 (71) 3283-6308 <br>
					Fax: +55 (71) 3283-6276</p>
				</div>

				<div>
					<i class="fa fa-envelope"></i>
					<p><a href="mailto:ceapgmat@ufba.br">ceapgmat@ufba.br</a></p>
				</div>

			</div>

			<div class="footer-right">

				<p class="footer-company-address">
					<span>Endereço:</span>
					Centro de Atendimento à Pós-Graduação (CEAPG), Instituto de Matemática e Estatística, Universidade Federal da Bahia - Av. Adhemar de Barros, s/n - Campus de Ondina - 1º Andar - Salvador - Bahia, CEP 40.170-110
				</p>

				

			</div>

		</footer>

 
  </body>
  
</html> 

app/views/disciplinas/edit.html.erb
<html lang="pt-br">
   <body>
 
      <header class="header">
     <h3>Estágio<span>Pró</span></h3>
     <p>Alocação de Estagiários Docentes</p>
   
     </header>
 
 
<h1>EDITAR DISCIPLINA</h1>

<%= render 'form', disciplina: @disciplina %>

       <button type="button" class="btn btn-primary"><%= link_to 'Exibir', @disciplina %> </button>
       <button type="button" class="btn btn-secondary"><%= link_to 'Voltar', disciplinas_path %></button>


<footer class="footer">

			<div class="footer-left">

				<h3>Estágio<span>Pró</span></h3>

				<p class="footer-company-name">EstagioPró &copy; 2018</p>
			</div>

			<div class="footer-center">

				<div>
					<i class="fa fa-map-marker"></i>
					<p><span>Universidade Federal da Bahia <br> 
                        Instituto de Matemática <br>
                        Departamento de Ciência da COmputação <br>
                        PGComp  - Programa de Pós Graduação em CIência da Computação </span>
				</div>

				<div>
					<i class="fa fa-phone"></i>
					<p>Telefone: +55 (71) 3283-6273 / +55 (71) 3283-6308 <br>
					Fax: +55 (71) 3283-6276</p>
				</div>

				<div>
					<i class="fa fa-envelope"></i>
					<p><a href="mailto:ceapgmat@ufba.br">ceapgmat@ufba.br</a></p>
				</div>

			</div>

			<div class="footer-right">

				<p class="footer-company-address">
					<span>Endereço:</span>
					Centro de Atendimento à Pós-Graduação (CEAPG), Instituto de Matemática e Estatística, Universidade Federal da Bahia - Av. Adhemar de Barros, s/n - Campus de Ondina - 1º Andar - Salvador - Bahia, CEP 40.170-110
				</p>

				

			</div>

		</footer>
 
  </body>
  
</html> 

app/views/disciplinas/index.html.erb
<html lang="pt-br">
   <body>
 
     <header class="header">
     <h3>Estágio<span>Pró</span></h3>
     <p>Alocação de Estagiários Docentes</p>
   
     </header>
 


<p id="notice"><%= notice %></p>

<h1>DISCIPLINAS</h1>

<table>
  <thead>
    <tr>
      <th>Nome disciplina</th>
      <th>Turma</th>
      <th>Dias de aula</th>
      <th>Horario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @disciplinas.each do |disciplina| %>
      <tr>
        <td><%= disciplina.Nome_disciplina %></td>
        <td><%= disciplina.Turma %></td>
        <td><%= disciplina.Dias_de_aula %></td>
        <td><%= disciplina.Horario %></td>
          <td><button type="button" class="btn btn-primary"><%= link_to 'Exibir', disciplina %></button></td>
          <td><button type="button" class="btn btn-secondary"><%= link_to 'Editar', edit_disciplina_path(disciplina) %></button></td>
          <td><button type="button" class="btn btn-danger"><%= link_to 'Deletar', disciplina, method: :delete, data: { confirm: 'Voce tem certeza?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

       <button type="button" class="btn btn-success"><%= link_to 'Nova Disciplina', new_disciplina_path %></button>



   <footer class="footer">

			<div class="footer-left">

				<h3>Estágio<span>Pró</span></h3>

				<p class="footer-company-name">EstagioPró &copy; 2018</p>
			</div>

			<div class="footer-center">

				<div>
					<i class="fa fa-map-marker"></i>
					<p><span>Universidade Federal da Bahia <br> 
                        Instituto de Matemática <br>
                        Departamento de Ciência da COmputação <br>
                        PGComp  - Programa de Pós Graduação em CIência da Computação </span>
				</div>

				<div>
					<i class="fa fa-phone"></i>
					<p>Telefone: +55 (71) 3283-6273 / +55 (71) 3283-6308 <br>
					Fax: +55 (71) 3283-6276</p>
				</div>

				<div>
					<i class="fa fa-envelope"></i>
					<p><a href="mailto:ceapgmat@ufba.br">ceapgmat@ufba.br</a></p>
				</div>

			</div>

			<div class="footer-right">

				<p class="footer-company-address">
					<span>Endereço:</span>
					Centro de Atendimento à Pós-Graduação (CEAPG), Instituto de Matemática e Estatística, Universidade Federal da Bahia - Av. Adhemar de Barros, s/n - Campus de Ondina - 1º Andar - Salvador - Bahia, CEP 40.170-110
				</p>

				

			</div>

		</footer>


 
  </body>
  
</html> 

app/views/disciplinas/new.html.erb
<html lang="pt-br">
   <body>
 
     <header class="header">
     <h3>Estágio<span>Pró</span></h3>
     <p>Alocação de Estagiários Docentes</p>
   
     </header>
 


<h1>NOVA DISCIPLINA</h1>
<div class="form">
<%= render 'form', disciplina: @disciplina %>

<button type="button" class="btn btn-primary"><%= link_to 'Voltar', disciplinas_path %></button>

</div>



   <footer class="footer">

			<div class="footer-left">

				<h3>Estágio<span>Pró</span></h3>

				<p class="footer-company-name">EstagioPró &copy; 2018</p>
			</div>

			<div class="footer-center">

				<div>
					<i class="fa fa-map-marker"></i>
					<p><span>Universidade Federal da Bahia <br> 
                        Instituto de Matemática <br>
                        Departamento de Ciência da COmputação <br>
                        PGComp  - Programa de Pós Graduação em CIência da Computação </span>
				</div>

				<div>
					<i class="fa fa-phone"></i>
					<p>Telefone: +55 (71) 3283-6273 / +55 (71) 3283-6308 <br>
					Fax: +55 (71) 3283-6276</p>
				</div>

				<div>
					<i class="fa fa-envelope"></i>
					<p><a href="mailto:ceapgmat@ufba.br">ceapgmat@ufba.br</a></p>
				</div>

			</div>

			<div class="footer-right">

				<p class="footer-company-address">
					<span>Endereço:</span>
					Centro de Atendimento à Pós-Graduação (CEAPG), Instituto de Matemática e Estatística, Universidade Federal da Bahia - Av. Adhemar de Barros, s/n - Campus de Ondina - 1º Andar - Salvador - Bahia, CEP 40.170-110
				</p>

				

			</div>

		</footer>

 
  </body>
  
</html> 

app/views/disciplinas/show.html.erb
<html lang="pt-br">
   <body>
 
     <header class="header">
     <h3>Estágio<span>Pró</span></h3>
     <p>Alocação de Estagiários Docentes</p>
   
     </header>
     
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome disciplina:</strong>
  <%= @disciplina.Nome_disciplina %>
</p>

<p>
  <strong>Turma:</strong>
  <%= @disciplina.Turma %>
</p>

<p>
  <strong>Dias de aula:</strong>
  <%= @disciplina.Dias_de_aula %>
</p>

<p>
  <strong>Horario:</strong>
  <%= @disciplina.Horario %>
</p>

<button type="button" class="btn btn-primary"><%= link_to 'Editar', edit_disciplina_path(@disciplina) %></button>
<button type="button" class="btn btn-secondary"><%= link_to 'Voltar', disciplinas_path %></button>


 <footer class="footer">

			<div class="footer-left">

				<h3>Estágio<span>Pró</span></h3>

				<p class="footer-company-name">EstagioPró &copy; 2018</p>
			</div>

			<div class="footer-center">

				<div>
					<i class="fa fa-map-marker"></i>
					<p><span>Universidade Federal da Bahia <br> 
                        Instituto de Matemática <br>
                        Departamento de Ciência da COmputação <br>
                        PGComp  - Programa de Pós Graduação em CIência da Computação </span>
				</div>

				<div>
					<i class="fa fa-phone"></i>
					<p>Telefone: +55 (71) 3283-6273 / +55 (71) 3283-6308 <br>
					Fax: +55 (71) 3283-6276</p>
				</div>

				<div>
					<i class="fa fa-envelope"></i>
					<p><a href="mailto:ceapgmat@ufba.br">ceapgmat@ufba.br</a></p>
				</div>

			</div>

			<div class="footer-right">

				<p class="footer-company-address">
					<span>Endereço:</span>
					Centro de Atendimento à Pós-Graduação (CEAPG), Instituto de Matemática e Estatística, Universidade Federal da Bahia - Av. Adhemar de Barros, s/n - Campus de Ondina - 1º Andar - Salvador - Bahia, CEP 40.170-110
				</p>

				

			</div>

		</footer>


 
  </body>
  
</html> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EstagioPro</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/professors/index.html.erb
<html lang="pt-br">
   <body>
 
     <header class="header">
     <h3>Estágio<span>Pró</span></h3>
     <p>Alocação de Estagiários Docentes</p>
   
     </header>

<p id="notice"><%= notice %></p>

<h1>PROFESSORES</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @professors.each do |professor| %>
      <tr>
        <td><%= professor.Nome %></td>
        <td><button type="button" class="btn btn-primary"><%= link_to 'Exibir', professor %></button></td>
          <td><button type="button" class="btn btn-secondary"><%= link_to 'Editar', edit_professor_path(professor) %></button></td>
          <td><button type="button" class="btn btn-danger"><%= link_to 'Deletar', professor, method: :delete, data: { confirm: 'Você tem certeza?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

       <button type="button" class="btn btn-success"><%= link_to 'Novo Professor', new_professor_path %></button>


<footer class="footer">

			<div class="footer-left">

				<h3>Estágio<span>Pró</span></h3>

				<p class="footer-company-name">EstagioPró &copy; 2018</p>
			</div>

			<div class="footer-center">

				<div>
					<i class="fa fa-map-marker"></i>
					<p><span>Universidade Federal da Bahia <br> 
                        Instituto de Matemática <br>
                        Departamento de Ciência da COmputação <br>
                        PGComp  - Programa de Pós Graduação em CIência da Computação </span>
				</div>

				<div>
					<i class="fa fa-phone"></i>
					<p>Telefone: +55 (71) 3283-6273 / +55 (71) 3283-6308 <br>
					Fax: +55 (71) 3283-6276</p>
				</div>

				<div>
					<i class="fa fa-envelope"></i>
					<p><a href="mailto:ceapgmat@ufba.br">ceapgmat@ufba.br</a></p>
				</div>

			</div>

			<div class="footer-right">

				<p class="footer-company-address">
					<span>Endereço:</span>
					Centro de Atendimento à Pós-Graduação (CEAPG), Instituto de Matemática e Estatística, Universidade Federal da Bahia - Av. Adhemar de Barros, s/n - Campus de Ondina - 1º Andar - Salvador - Bahia, CEP 40.170-110
				</p>

				

			</div>

		</footer>

 
  </body>
  
</html> 

app/views/professors/show.html.erb
<html lang="pt-br">
   <body>
 
    <header class="header">
     <h3>Estágio<span>Pró</span></h3>
     <p>Alocação de Estagiários Docentes</p>
   
     </header>
     
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @professor.Nome %>
</p>

       <button type="button" class="btn btn-primary"><%= link_to 'Editar', edit_professor_path(@professor) %></button>
       <button type="button" class="btn btn-secondary"><%= link_to 'Voltar', professors_path %></button>



 <footer class="footer">

			<div class="footer-left">

				<h3>Estágio<span>Pró</span></h3>

				
				<p class="footer-company-name">EstagioPró &copy; 2018</p>
			</div>

			<div class="footer-center">

				<div>
					<i class="fa fa-map-marker"></i>
					<p><span>Universidade Federal da Bahia <br> 
                        Instituto de Matemática <br>
                        Departamento de Ciência da COmputação <br>
                        PGComp  - Programa de Pós Graduação em CIência da Computação </span>
				</div>

				<div>
					<i class="fa fa-phone"></i>
					<p>Telefone: +55 (71) 3283-6273 / +55 (71) 3283-6308 <br>
					Fax: +55 (71) 3283-6276</p>
				</div>

				<div>
					<i class="fa fa-envelope"></i>
					<p><a href="mailto:ceapgmat@ufba.br">ceapgmat@ufba.br</a></p>
				</div>

			</div>

			<div class="footer-right">

				<p class="footer-company-address">
					<span>Endereço:</span>
					Centro de Atendimento à Pós-Graduação (CEAPG), Instituto de Matemática e Estatística, Universidade Federal da Bahia - Av. Adhemar de Barros, s/n - Campus de Ondina - 1º Andar - Salvador - Bahia, CEP 40.170-110
				</p>

				

			</div>

		</footer>
   
    
    
    </body>
</html>